version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:00"  # UTC (JST 6:00 AM)
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      all-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "pydantic*"  # Exclude pydantic packages to avoid version conflicts
    ignore:
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "pydantic-core"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
