version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:00"  # UTC (JST 6:00 AM)
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      all-dependencies:
        patterns:
          - "*"
