# Pre-commit hooks for code quality
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      # Run the formatter
      - id: ruff-format
        types_or: [python, pyi]

  # Full test suite execution for comprehensive quality assurance
  - repo: local
    hooks:
      - id: pytest-all
        name: Run full test suite
        entry: uv run pytest
        args: [--tb=short, --maxfail=5, -v]
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

# MyPy type checking - currently disabled due to extensive type annotation work needed
# Will be re-enabled gradually as type coverage improves
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.13.0
#   hooks:
#     - id: mypy
#       additional_dependencies:
#         - types-python-dateutil
#         - types-requests
#       exclude: ^(tests/|migrations/)
#       args: [--ignore-missing-imports, --scripts-are-modules, --no-strict-optional, --allow-untyped-defs, --allow-incomplete-defs, --no-warn-return-any, --allow-untyped-calls]
