"""Tests for the standard error envelope (Issue #76).

Validates that:
  * Domain exceptions are rendered with the new ``ErrorResponse``
    fields (``error``, ``message``, ``status_code``, ``timestamp``,
    ``request_id``) while keeping the legacy ``detail`` mirror.
  * ``RequestValidationError`` (422) populates ``details`` with
    per-field errors.
  * ``HTTPException`` falls back to a synthesised ``HTTP_<code>`` and
    unhandled exceptions become ``INTERNAL_ERROR`` (500).
  * The ``X-Request-ID`` request header is honored when present and
    surfaces in the response payload.
"""

from __future__ import annotations

from fastapi import FastAPI, HTTPException
from fastapi.testclient import TestClient
from pydantic import BaseModel

from app.core.error_handlers import register_exception_handlers
from app.core.exceptions import (
    ConflictException,
)
from app.core.exceptions import (
    ServerNotFoundException as LegacyServerNotFoundException,
)
from app.groups.domain.exceptions import (
    GroupAccessError,
    GroupAlreadyExistsError,
    GroupNotFoundError,
)
from app.middleware.audit_middleware import AuditMiddleware
from app.servers.domain.exceptions import (
    ServerAccessError,
    ServerNotFoundError,
)
from app.templates.domain.exceptions import TemplateNotFoundError


class _ValidationBody(BaseModel):
    """Top-level model used by the validation-error tests.

    Declared at module scope (rather than inside ``_build_app``) so
    Pydantic v2's schema builder can resolve forward references — when
    defined locally, the validator was treating the whole request body
    as a single failing field rather than per-field errors.
    """

    name: str
    count: int


def _build_app() -> FastAPI:
    """Build a minimal app with the audit middleware + error handlers.

    The audit middleware is required so ``request.state.request_id`` is
    populated; without it the handlers would still respond but with
    ``request_id=None``.
    """
    app = FastAPI()
    register_exception_handlers(app)
    app.add_middleware(AuditMiddleware, enabled=True, exclude_health_checks=False)

    @app.get("/raise-server-not-found")
    def _server_nf():
        raise ServerNotFoundError("nope")

    @app.get("/raise-server-access")
    def _server_access():
        raise ServerAccessError("forbidden")

    @app.get("/raise-group-not-found")
    def _group_nf():
        raise GroupNotFoundError("missing")

    @app.get("/raise-group-access")
    def _group_access():
        raise GroupAccessError("forbidden")

    @app.get("/raise-group-exists")
    def _group_exists():
        raise GroupAlreadyExistsError("dup")

    @app.get("/raise-template-not-found")
    def _template_nf():
        raise TemplateNotFoundError("nope")

    @app.get("/raise-legacy-not-found")
    def _legacy_nf():
        raise LegacyServerNotFoundException("42")

    @app.get("/raise-legacy-conflict")
    def _legacy_conflict():
        raise ConflictException("clash")

    @app.get("/raise-http-exception")
    def _http():
        raise HTTPException(status_code=418, detail="teapot")

    @app.get("/raise-unhandled")
    def _unhandled():
        raise RuntimeError("boom")

    @app.post("/validate")
    def _validate(body: _ValidationBody):
        return {"ok": True}

    return app


def _client() -> TestClient:
    return TestClient(_build_app())


class TestDomainExceptionHandlers:
    def test_server_not_found(self):
        c = _client()
        r = c.get("/raise-server-not-found")
        assert r.status_code == 404
        body = r.json()
        assert body["error"] == "SERVER_NOT_FOUND"
        assert body["status_code"] == 404
        assert body["message"] == "nope"
        # Legacy mirror retained for backward compatibility.
        assert body["detail"] == "nope"
        assert "timestamp" in body and body["timestamp"]
        # request_id was generated by the audit middleware
        assert body["request_id"]
        # Response header also carries the request ID
        assert r.headers.get("X-Request-ID") == body["request_id"]

    def test_server_access_denied(self):
        r = _client().get("/raise-server-access")
        assert r.status_code == 403
        body = r.json()
        assert body["error"] == "SERVER_ACCESS_DENIED"
        assert body["detail"] == "forbidden"

    def test_group_not_found(self):
        r = _client().get("/raise-group-not-found")
        assert r.status_code == 404
        body = r.json()
        assert body["error"] == "GROUP_NOT_FOUND"

    def test_group_access_denied(self):
        r = _client().get("/raise-group-access")
        assert r.status_code == 403
        assert r.json()["error"] == "GROUP_ACCESS_DENIED"

    def test_group_already_exists(self):
        r = _client().get("/raise-group-exists")
        assert r.status_code == 400
        assert r.json()["error"] == "GROUP_ALREADY_EXISTS"

    def test_template_not_found(self):
        r = _client().get("/raise-template-not-found")
        assert r.status_code == 404
        assert r.json()["error"] == "TEMPLATE_NOT_FOUND"


class TestLegacyAPIExceptionHandler:
    def test_legacy_not_found_emits_structured_envelope(self):
        r = _client().get("/raise-legacy-not-found")
        assert r.status_code == 404
        body = r.json()
        # Legacy APIException subclass carries error_code via ClassVar.
        assert body["error"] == "SERVER_NOT_FOUND"
        assert "Server with ID 42 not found" in body["detail"]
        assert body["detail"] == body["message"]

    def test_legacy_conflict(self):
        r = _client().get("/raise-legacy-conflict")
        assert r.status_code == 409
        body = r.json()
        assert body["error"] == "RESOURCE_CONFLICT"
        assert body["detail"] == "clash"


class TestValidationErrorHandler:
    def test_field_errors_present_in_details(self):
        c = _client()
        # ``count`` wrong type and ``extra_unused`` ignored.
        # Provide both keys so Pydantic produces a per-field error
        # rather than a single "body required" entry.
        r = c.post("/validate", json={"name": "ok", "count": "not-a-number"})
        assert r.status_code == 422
        body = r.json()
        assert body["error"] == "VALIDATION_ERROR"
        assert body["status_code"] == 422
        details = body.get("details") or []
        assert len(details) >= 1
        fields = {d.get("field") for d in details}
        assert "count" in fields
        for d in details:
            assert isinstance(d.get("message"), str) and d["message"]

    def test_missing_body_yields_validation_error(self):
        c = _client()
        # Empty body — single error pointing at body
        r = c.post("/validate", json={})
        assert r.status_code == 422
        body = r.json()
        assert body["error"] == "VALIDATION_ERROR"
        details = body.get("details") or []
        assert len(details) >= 1
        # Each detail still carries a message + code
        for d in details:
            assert d.get("message")


class TestHTTPExceptionFallback:
    def test_unknown_http_exception(self):
        r = _client().get("/raise-http-exception")
        assert r.status_code == 418
        body = r.json()
        assert body["error"] == "HTTP_418"
        assert body["detail"] == "teapot"
        assert body["message"] == "teapot"


class TestUnhandledExceptionFallback:
    def test_500_uses_internal_error_code(self):
        # Disable raise_server_exceptions so TestClient returns the
        # exception handler's 500 response rather than re-raising.
        client = TestClient(_build_app(), raise_server_exceptions=False)
        r = client.get("/raise-unhandled")
        assert r.status_code == 500
        body = r.json()
        assert body["error"] == "INTERNAL_ERROR"
        assert body["message"] == "An internal server error occurred"
        assert body["detail"] == body["message"]


class TestRequestIDPropagation:
    def test_inbound_request_id_header_is_honored(self):
        r = _client().get(
            "/raise-server-not-found",
            headers={"X-Request-ID": "my-trace-1234"},
        )
        assert r.status_code == 404
        body = r.json()
        assert body["request_id"] == "my-trace-1234"
        assert r.headers.get("X-Request-ID") == "my-trace-1234"

    def test_blank_request_id_header_falls_back_to_uuid(self):
        r = _client().get(
            "/raise-server-not-found",
            headers={"X-Request-ID": "   "},
        )
        body = r.json()
        # UUID4 is 36 chars
        assert body["request_id"] and body["request_id"] != "   "
        assert len(body["request_id"]) == 36

    def test_oversized_request_id_header_is_rejected(self):
        long_id = "x" * 200
        r = _client().get(
            "/raise-server-not-found",
            headers={"X-Request-ID": long_id},
        )
        body = r.json()
        assert body["request_id"] != long_id
        assert len(body["request_id"]) == 36
