name: CI

on:
  push:
    branches:
      - "**"

jobs:
  ci:
    name: Test, Lint, Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.13.3"

      - name: Create .env file
        run: |
          echo "SECRET_KEY=test-secret-key-for-ci-pipeline-32-chars-long" >> .env
          echo "ALGORITHM=HS256" >> .env
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> .env
          echo "DATABASE_URL=sqlite:///./test.db" >> .env

      - name: Install dependencies
        run: uv sync

      - name: Run formatter (ruff)
        run: uv run ruff format app/ --check

      - name: Run linter (ruff)
        run: uv run ruff check app/

      - name: Run tests (pytest)
        run: uv run pytest
